commerce_viva.commerce_payment_gateway.plugin.viva_redirect_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    api_key:
      type: string
      label: 'API key'
    website_code:
      type: string
      label: 'Website code (source code)'
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    brand_color:
      type: string
      label: 'Brand color'
